Include @NGINX_DIR@/modsecurity.conf
Include /opt/liteedge/etc/crs/crs-setup.conf
Include /opt/liteedge/etc/crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
SecAction "id:1000001,phase:1,nolog,pass,setvar:tx.crs_exclusions_wordpress=1"
Include /opt/liteedge/etc/crs/rules/*.conf
Include /opt/liteedge/etc/crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
